package com.sample.microservice.awsdynamodb.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
/*

@Data
@DynamoDBTable(tableName = "employee")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Employee  {

    @DynamoDBHashKey(attributeName = "pk")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "FirstName")
    private String firstName;

    @DynamoDBAttribute(attributeName = "LastName")
    private String lastName;

    @DynamoDBAttribute(attributeName = "Number")
    private String number;

    @DynamoDBAttribute(attributeName = "Email")
    private String email;

    @DynamoDBAttribute(attributeName = "Department")
    private String department;

    @DynamoDBAttribute(attributeName = "Salary")
    private double salary;
}
*/


@DynamoDBTable(tableName = "Employee")
public class Employee  {

    private String id;

    private String firstName;

    private String lastName;

    private String number;

    private String email;

    private String department;

    private int salary;




    public Employee() {
        // Default constructor is required by AWS DynamoDB SDK
    }

    public Employee(String id, String firstName, String lastName, String number, String email, String department, int salary) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.number = number;
        this.email = email;
        this.department = department;
        this.salary = salary;
    }

    @DynamoDBHashKey(attributeName="Id")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "FirstName")
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @DynamoDBAttribute(attributeName = "LastName")
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @DynamoDBAttribute(attributeName = "Number")
    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    @DynamoDBAttribute(attributeName = "Email")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @DynamoDBAttribute(attributeName = "Department")
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    @DynamoDBAttribute(attributeName = "Salary")
    public int getSalary() {
        return salary;
    }

    public void setSalary(int salary) {
        this.salary = salary;
    }
}
